/*****************************************************************************
Copyright (c) 2019 - Analog Devices Inc. All Rights Reserved.
This software is proprietary & confidential to Analog Devices, Inc.
and its licensors.
 ******************************************************************************
File Name : main.c

Generation Date: 2019-01-09
Generated By: Jens Sorensen

Description:

 *****************************************************************************/

/*=============  I N C L U D E S   =============*/
#include "platform.h"
#include "application.h"

#include <stdint.h>
#include <stdio.h>
#include <time.h>

#include "platform.h"
#include "ADIMonitor.h"
#include "alt_timers.h"

/*=============  D E F I N E S   =============*/

/*=============  P R O T O T Y P E S  =============*/

/*=============  D A T A  =============*/


extern int32_t UART_TxIsrCounter, UART_RxIsrCounter;

static int led_flagGPIO_LED2 = 1;
static int led_flagGPIO_LED3 = 1;
static int led_flagGPIO_LED4 = 1;
static int led_flagGPIO_LED5 = 1;
static int led_flagGPIO_LED6 = 1;
static int led_flagGPIO_LED7 = 1;
#define TOGGLE_LED(n) { SetLed(n,led_flag##n);led_flag##n = !led_flag##n; }
/*=============  C O D E  ==================*/

int main(void){
	static int cnt=0;
	volatile uint32_t* reg = (volatile uint32_t*)0xFF200000;

	platformInit();

	time_t fpga_build_time = reg[1];

	printf("\r\n");
	printf("App Build Timestamp = %s %s\r\n", __DATE__, __TIME__);
	printf("FPGA Build ID = 0x%08x. Timestamp = %s\r\n", (int)reg[0],
			ctime(&fpga_build_time));
	UNUSED(led_flagGPIO_LED2);
	UNUSED(led_flagGPIO_LED3);
	UNUSED(led_flagGPIO_LED4);
	UNUSED(led_flagGPIO_LED5);
	UNUSED(led_flagGPIO_LED6);
	UNUSED(led_flagGPIO_LED7);

	aAppInit();

	for(int ii = 0; ii < 100; ++ii) {
		TOGGLE_LED(GPIO_LED2);
		checkTxBuffer();
	}

	// disable console so as to not corrupt uart with logging
	enable_console(0);

	while(1){
		TOGGLE_LED(GPIO_LED2);
		checkRxUart();
		checkTxBuffer();
		cnt++;
	}
	return 1;
}
