/*****************************************************************************
Copyright (c) 2019 - Analog Devices Inc. All Rights Reserved.
This software is proprietary & confidential to Analog Devices, Inc.
and its licensors.
******************************************************************************
File Name : main.c

Generation Date: 2019-01-09
Generated By: Jens Sorensen

Description:

*****************************************************************************/

/*=============  I N C L U D E S   =============*/
#include "platform.h"
#include "application.h"

#include <stdint.h>
#include <stdio.h>
#include <time.h>

#include <alt_interrupt.h>
#include <alt_generalpurpose_io.h>

/*=============  D E F I N E S   =============*/

/*=============  P R O T O T Y P E S  =============*/

/*=============  D A T A  =============*/

/*=============  C O D E  ==================*/

extern int32_t UART_TxIsrCounter, UART_RxIsrCounter;

int main(void){
  static int cnt=0;

  volatile uint32_t* reg = (volatile uint32_t*)0xFF200000;

  time_t fpga_build_time = reg[1];

  printf("\r\n");
  printf("FPGA Build ID = 0x%08x. Timestamp = %s\r", (int)reg[0],
    ctime(&fpga_build_time));

  alt_gpio_init();
  // Use alt_gpio_port_datadir_set to turn on/off LEDs
  // LED0 = N/A (FPGA direct connect)
  // LED1 = ALT_GPIO_PORTB, ALT_GPIO_BIT21 ??
  // LED2 = ALT_GPIO_PORTB, ALT_GPIO_BIT20
  // LED3 = ALT_GPIO_PORTB, ALT_GPIO_BIT19
  // LED4 = ALT_GPIO_PORTB, ALT_GPIO_BIT15
  // LED5 = ALT_GPIO_PORTB, ALT_GPIO_BIT11
  // LED6 = ALT_GPIO_PORTB, ALT_GPIO_BIT12
  // LED7 = ALT_GPIO_PORTB, ALT_GPIO_BIT13 
    alt_gpio_port_datadir_set(ALT_GPIO_PORTB, GPIO_LED5, GPIO_LED5);

  // These must be only called once (setup for being able to use interrupts)
  alt_int_global_init();
  alt_int_cpu_init();

  platformInit();
  aAppInit();

  // These must be only called once (enables interrupts now that all setup is complete)
  alt_int_cpu_enable();
  alt_int_global_enable();

  while(1){
	AdiMonitor();  // Call monitor program to capture data
	cnt++;
  }

  return 1;
}
