/*******************************************************************************
Copyright (c) 2016 - Analog Devices Inc. All Rights Reserved.
This software is proprietary & confidential to Analog Devices, Inc.
and its licensors.
********************************************************************************
File Name: platform.c

Generation Date: 2016-10-24
Generated By: Christian Aaen
*******************************************************************************/

#include "platform.h"
#include <stddef.h>

//TODO: we need altera equivalent for these??
/*
#include <xstatus.h>
#include <xparameters.h>
#include <xil_exception.h>
#include <xscugic.h>
#include <xgpiops.h>

static XScuGic_Config* pGicConfig = NULL;
static XGpioPs_Config* pGpioConfig = NULL;

xilInstance_t xilInstance;

static sfeStatus_t gpioInit(void)
{
    int status;

    pGpioConfig = XGpioPs_LookupConfig(XPAR_XGPIOPS_0_DEVICE_ID);

    if (pGicConfig == NULL)
    {
        //DEBUG_ERROR("XGpioPs_LookupConfig", 0);
        return SFE_DRIVER_ERROR;
    }

    status = XGpioPs_CfgInitialize(&xilInstance.gpio, pGpioConfig, pGpioConfig->BaseAddr);

    if (status != XST_SUCCESS)
    {
        //DEBUG_ERROR("XGpioPs_CfgInitialize", status);
        return SFE_DRIVER_ERROR;
    }

    return SFE_SUCCESS;
}

static sfeStatus_t gicInit(void)
{
    int status;

    pGicConfig = XScuGic_LookupConfig(XPAR_SCUGIC_0_DEVICE_ID);

    if (pGicConfig == NULL)
    {
        //DEBUG_ERROR("XScuGic_LookupConfig", 0);
        return SFE_DRIVER_ERROR;
    }

    status = XScuGic_CfgInitialize(&xilInstance.gic, pGicConfig, pGicConfig->CpuBaseAddress);

    if (status != XST_SUCCESS)
    {
        //DEBUG_ERROR("XScuGic_CfgInitialize", status);
        return SFE_DRIVER_ERROR;
    }

    Xil_ExceptionRegisterHandler(XIL_EXCEPTION_ID_INT, (Xil_InterruptHandler) XScuGic_InterruptHandler, &xilInstance.gic);
    Xil_ExceptionEnable();

    return SFE_SUCCESS;
}
*/

sfeStatus_t platformInit(void)
{
/*
    sfeStatus_t status = SFE_SUCCESS;

    status = gicInit();

    if (status != SFE_SUCCESS)
        return status;

    status = gpioInit();

    if (status != SFE_SUCCESS)
        return status;
*/

    return SFE_SUCCESS;
}
