# TCL File Generated by Component Editor 17.1
# Wed Jan 03 09:57:20 EST 2018
# DO NOT MODIFY


# 
# qep_ip "Deserializer" v1.0
#  2018.01.03.09:57:20
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.0


# 
# module qep_ip
# 
set_module_property DESCRIPTION ""
set_module_property NAME qep_ip
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME qep_ip
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL qep_ip
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file qep_ip.vhd VHDL PATH qep_ip.vhd TOP_LEVEL_FILE
add_fileset_file qep_ip.sdc SDC PATH qep_ip.sdc
add_fileset_file min_pulse_width.v VERILOG PATH min_pulse_width.v
add_fileset_file quadrature_decoder.v VERILOG PATH quadrature_decoder.v
add_fileset_file sync_domain.v VERILOG PATH sync_domain.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock reg_clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock reg_clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr i_reg_addr address Input 7
add_interface_port csr i_reg_read_en read Input 1
add_interface_port csr o_reg_readdata readdata Output 32
add_interface_port csr i_reg_write_en write Input 1
add_interface_port csr i_reg_writedata writedata Input 32
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reg_clock
# 
add_interface reg_clock clock end
set_interface_property reg_clock clockRate 0
set_interface_property reg_clock ENABLED true
set_interface_property reg_clock EXPORT_OF ""
set_interface_property reg_clock PORT_NAME_MAP ""
set_interface_property reg_clock CMSIS_SVD_VARIABLES ""
set_interface_property reg_clock SVD_ADDRESS_GROUP ""

add_interface_port reg_clock i_reg_clk clk Input 1


# 
# connection point qep_sigs
# 
add_interface qep_sigs conduit end
set_interface_property qep_sigs associatedClock "" 
set_interface_property qep_sigs associatedReset ""
set_interface_property qep_sigs ENABLED true
set_interface_property qep_sigs EXPORT_OF ""
set_interface_property qep_sigs PORT_NAME_MAP ""
set_interface_property qep_sigs CMSIS_SVD_VARIABLES ""
set_interface_property qep_sigs SVD_ADDRESS_GROUP ""

add_interface_port qep_sigs A A Input 1
add_interface_port qep_sigs B B Input 1
add_interface_port qep_sigs Z Z Input 1
add_interface_port qep_sigs HALL HALL Input 3
add_interface_port qep_sigs sync_strobe sync_strobe Input 1
