/*****************************************************************************
Copyright (c) 2013 - Analog Devices Inc. All Rights Reserved.
This software is proprietary & confidential to Analog Devices, Inc.
and its licensors.
******************************************************************************
File Name : application.h 

Generation Date: 2013-09-12
Generated By: Jens Sorensen 

Description: 

*****************************************************************************/

/*=============  D E F I N E S  =============*/
typedef enum {    
  eAPP_START,
  eAPP_STOP,
  eAPP_FAULT
} APP_EVENT;

typedef enum {    
  sMOTOR_STOPPED,
  sMOTOR_RUNNING,
  sMOTOR_FAULT
} APP_STATE_TYPE;

typedef enum {
  LV_PLATFORM,
  HV_PLATFORM
} PLATFORM_TYPE;

/*=============  EXTERNAL FUNCTIONS  =============*/
void aAppInit(void);
void aAppCmd(APP_EVENT);
void sAppTask(void);

/*=============  EXTERNAL VARIABLES  =============*/
extern PLATFORM_TYPE platform_id;
