/*******************************************************************************
Copyright (c) 2016 - Analog Devices Inc. All Rights Reserved.
This software is proprietary & confidential to Analog Devices, Inc.
and its licensors.
********************************************************************************
File Name: platform.h

Generation Date: 2016-10-24
Generated By: Christian Aaen
*******************************************************************************/

#ifndef PLATFORM_H_
#define PLATFORM_H_
#include <hwlib.h>
#include <alt_generalpurpose_io.h>

//TODO: we need altera equivalent of any of this??
/*
#include <xscugic.h>
#include <xgpiops.h>

//#include "sfe_status.h"

typedef struct
{
    XScuGic gic;
    XGpioPs gpio;
} xilInstance_t;

extern xilInstance_t xilInstance;
*/

typedef enum
{
    SFE_SUCCESS,
    SFE_DRIVER_ERROR
} sfeStatus_t;

typedef float         real32_t;

sfeStatus_t platformInit(void);

#define	UART_IRQ_PRIORITY			20
#define	SINC_DATA_IRQ_PRIORITY		21
#define	MOTOR_PWM_IRQ_PRIORITY		22

//#dfine GPIO_LED0 = N/A (FPGA direct connect)
#define GPIO_LED1 ALT_GPIO_BIT21
#define GPIO_LED2 ALT_GPIO_BIT20
#define GPIO_LED3 ALT_GPIO_BIT19
#define GPIO_LED4 ALT_GPIO_BIT15
#define GPIO_LED5 ALT_GPIO_BIT11
#define GPIO_LED6 ALT_GPIO_BIT12
#define GPIO_LED7 ALT_GPIO_BIT13

inline void SetLed(uint32_t led, int on)
{
	alt_gpio_port_datadir_set(ALT_GPIO_PORTB, led, on?led:0);
}
#endif
