/*******************************************************************************
Copyright (c) 2016 - Analog Devices Inc. All Rights Reserved.
This software is proprietary & confidential to Analog Devices, Inc.
and its licensors.
********************************************************************************
File Name: platform.h

Generation Date: 2016-10-24
Generated By: Christian Aaen
*******************************************************************************/

#ifndef PLATFORM_H_
#define PLATFORM_H_

//TODO: we need altera equivalent of any of this??
/*
#include <xscugic.h>
#include <xgpiops.h>

//#include "sfe_status.h"

typedef struct
{
    XScuGic gic;
    XGpioPs gpio;
} xilInstance_t;

extern xilInstance_t xilInstance;
*/

typedef enum
{
    SFE_SUCCESS,
    SFE_DRIVER_ERROR
} sfeStatus_t;

typedef float         real32_t;

sfeStatus_t platformInit(void);

#endif
