/*****************************************************************************
Copyright (c) 2019 - Analog Devices Inc. All Rights Reserved.
This software is proprietary & confidential to Analog Devices, Inc.
and its licensors.
******************************************************************************
File Name : pwm.h

Generation Date: 2019-01-09
Generated By: Jens Sorensen

Description:

*****************************************************************************/
#include <stdint.h>
#include <platform.h>

#define BITM_EXT_TRIP 0x1
#define BITM_SINC0_TRIP 0x2
#define BITM_SINC1_TRIP_MASK 0x4

/*=============  D E F I N E S  =============*/
typedef struct
{
    uint16_t duty_a;
    uint16_t duty_b;
	uint16_t duty_c;
} duty_type;

/*=============  EXTERNAL FUNCTIONS  =============*/
void InitPWM(void);
void ClearPwmTrip(void);
void SetDuty(duty_type *);
void DisablePWM(void);
void EnablePWM(void);
uint8_t GetPwmTripStatus(void);
uint8_t GetPwmTripPinLevel(void);
uint8_t GetPwmTripSource(void);

/*=============  EXTERNAL VARIABLES  =============*/



