/*****************************************************************************
Copyright (c) 2019 - Analog Devices Inc. All Rights Reserved.
This software is proprietary & confidential to Analog Devices, Inc.
and its licensors.
******************************************************************************
File Name : qep.h

Generation Date: 2019-01-09
Generated By: Jens Sorensen

Description:

*****************************************************************************/
#include <stdint.h>
#include "rtwtypes.h"
/*=============  D E F I N E S  =============*/

/*=============  EXTERNAL FUNCTIONS  =============*/
void aInitIncEnc(void);
void GetQepRegs(uint32_T*, uint32_T*, uint32_T*, int8_T*);
void GetQepRegsStrobeLatch(uint32_T*, uint32_T*, uint32_T*, int8_T*);
uint16_t GetHallState(void);
/*=============  EXTERNAL VARIABLES  =============*/
