# TCL File Generated by Component Editor 17.1
# Wed Jan 03 09:57:20 EST 2018
# DO NOT MODIFY


# 
# sinc_flush_trip_ip "Deserializer" v1.0
#  2018.01.03.09:57:20
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.0


# 
# module sinc_flush_trip_ip
# 
set_module_property DESCRIPTION ""
set_module_property NAME sinc_flush_trip_ip
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME sinc_flush_trip_ip
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sinc_flush_trip_ip
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sinc_flush_trip_ip.vhd VHDL PATH sinc_flush_trip_ip.vhd TOP_LEVEL_FILE
add_fileset_file sinc_flush_trip_ip.sdc SDC PATH sinc_flush_trip_ip.sdc
add_fileset_file sinc_clk.v VERILOG PATH sinc_clk.v
add_fileset_file sinc_module.v VERILOG PATH sinc_module.v
add_fileset_file sinc_trip.v VERILOG PATH sinc_trip.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock reg_clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock reg_clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr i_reg_addr address Input 7
add_interface_port csr i_reg_read_en read Input 1
add_interface_port csr o_reg_readdata readdata Output 32
add_interface_port csr i_reg_write_en write Input 1
add_interface_port csr i_reg_writedata writedata Input 32
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reg_clock
# 
add_interface reg_clock clock end
set_interface_property reg_clock clockRate 0
set_interface_property reg_clock ENABLED true
set_interface_property reg_clock EXPORT_OF ""
set_interface_property reg_clock PORT_NAME_MAP ""
set_interface_property reg_clock CMSIS_SVD_VARIABLES ""
set_interface_property reg_clock SVD_ADDRESS_GROUP ""

add_interface_port reg_clock i_reg_clk clk Input 1


#                                                                               
# connection point irq0                                                         
#                                                                               
add_interface irq0 interrupt end                                                
set_interface_property irq0 associatedAddressablePoint csr                       
set_interface_property irq0 associatedClock reg_clock
set_interface_property irq0 associatedReset reset                               
set_interface_property irq0 ENABLED true                                        
set_interface_property irq0 EXPORT_OF ""                                        
set_interface_property irq0 PORT_NAME_MAP ""                                    
set_interface_property irq0 CMSIS_SVD_VARIABLES ""                              
set_interface_property irq0 SVD_ADDRESS_GROUP ""                                
                                                                                
add_interface_port irq0 o_irq irq Output 1 


# 
# connection point sinc_flush_trip_sigs
# 
add_interface sinc_flush_trip_sigs conduit end
set_interface_property sinc_flush_trip_sigs associatedClock "" 
set_interface_property sinc_flush_trip_sigs associatedReset ""
set_interface_property sinc_flush_trip_sigs ENABLED true
set_interface_property sinc_flush_trip_sigs EXPORT_OF ""
set_interface_property sinc_flush_trip_sigs PORT_NAME_MAP ""
set_interface_property sinc_flush_trip_sigs CMSIS_SVD_VARIABLES ""
set_interface_property sinc_flush_trip_sigs SVD_ADDRESS_GROUP ""

add_interface_port sinc_flush_trip_sigs o_sinc0_data_irq o_sinc0_data_irq Output 1
add_interface_port sinc_flush_trip_sigs SINC_MCLK SINC_MCLK Output 1
add_interface_port sinc_flush_trip_sigs SINC0_TRIP SINC0_TRIP Output 1
add_interface_port sinc_flush_trip_sigs SINC1_TRIP SINC1_TRIP Output 1
add_interface_port sinc_flush_trip_sigs SINC_D0 SINC_D0 Input 1
add_interface_port sinc_flush_trip_sigs SINC_D1 SINC_D1 Input 1
add_interface_port sinc_flush_trip_sigs PWM_SYNC PWM_SYNC Input 1
