/*****************************************************************************
Copyright (c) 2012 - Analog Devices Inc. All Rights Reserved.
This software is proprietary & confidential to Analog Devices, Inc.
and its licensors.
******************************************************************************
File Name : sv_mod.c 

Generation Date: 2012-05-16 
Generated By: Jens Sorensen 

Description: This file implements a space vector modulator by calculating the zero 
sequence and adding it to the reference. 

*****************************************************************************/

/*=============  C O D E  =============*/
/*****************************************************************************
  Function: SvModulator

  Space Vector Modulator. Takes 3 reference voltages as input and calculates 
  duty-cycles. Funtions called from S-function and is prototyped in S-function builder

  Parameters: u0,u1,u2; Pointers to voltage references
			  u3; Pointer to modulator selector
			  y0,y1,y2; pointers to duty-cycles (where result is stored)
 
  Returns: None

*****************************************************************************/
void SvModulator(const float *u0, const float *u1, const float *u2, const unsigned char *u3, float *y0, float *y1, float *y2)
{
  float u0_abs, u1_abs, u2_abs; // Absolute value of references
  float v_0;					// Zero-sequence voltage

  if(*u3==1){
	if(*u0 < 0)					// Find absolute vaule of all references
	  u0_abs = -*u0;
    else
	  u0_abs = *u0;
	
    if(*u1 < 0)
	  u1_abs = -*u1;
    else
  	  u1_abs = *u1;
	
    if(*u2 < 0)
	  u2_abs = -*u2;
    else
  	  u2_abs = *u2;	
    
	if( u0_abs<u1_abs && u0_abs<u2_abs )		// |va| is smallest
	  v_0 = *u0*0.5;
    else if( u1_abs<u0_abs && u1_abs<u2_abs )	// |vb| is smallest
	  v_0 = *u1*0.5;
    else										// |vc| is smallest
      v_0 = *u2*0.5;
  }
  else{
    v_0 = 0;
  }

  *y0=*u0+v_0;
  *y1=*u1+v_0;
  *y2=*u2+v_0;
}

/* End Of File */

